sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.8
jdk:
  - openjdk8
install:
  # The default ivy resolution takes way too much time, and times out Travis builds.
  # We use coursier instead.
  - mkdir -p $HOME/.sbt/1.0/plugins/
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0")' > $HOME/.sbt/1.0/plugins/coursier.sbt
script:
  - sbt ++$TRAVIS_SCALA_VERSION jsdependencies-core/test jsdependencies-core/doc
  - |
      if [[ "${TRAVIS_SCALA_VERSION}" == "2.12.8" ]]; then
        sbt ++$TRAVIS_SCALA_VERSION jsdependencies-core/publishLocal sbt-jsdependencies/publishLocal && \
        cd sbt-plugin-test && \
        sbt testAll && \
        cd ..
      fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
  - rm $HOME/.sbt/1.0/plugins/coursier.sbt
